server:
  port: 8100

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  boot:
    admin:
      client:
        url: http://localhost:8001
foo : "this is demo  dev"