server:
  port: 80

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

spring:

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      #      路由路径
      routes:
        - id: demo
          uri:  http://localhost:8100/
          predicates:
            - Path=/demo/**
  boot:
    admin:
      client:
        url: http://localhost:8001